apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
     env  : prod
     owner: VladimirNechay
spec:
  selector:
    project: main      # Selecting PODs with those Labels
  ports:
    - name      : app-listener
#      protocol  : HTTP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on Pod
    - name      : app-listener2
      port      : 443
      targetPort: 80
  type: LoadBalancer
