apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  labels:
    app: main

spec:
  replicas: 1
  selector:
    matchLabels:
      project: main
  template:
    metadata:
      labels:
        project: main
    spec:
      containers:
        - name: main
          image: vladimir99/apache-alpine:latest
          ports:
            - containerPort: 80
